# Generated by Django 3.0.6 on 2020-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uniqemailuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='uniqemailuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
