# Generated by Django 3.0.4 on 2020-03-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager_backend_api', '0002_currency_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='currency',
        ),
    ]
