# Generated by Django 3.0.4 on 2020-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_manager_backend_api', '0003_remove_debtor_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='current',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
