version: '3.8'
services:
    debt-manager:
        build:
            context: .
            network: host
        command: bash -c "cd /code/ && python manage.py test && python manage.py migrate --noinput && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=
            - GOOGLE_RECAPTCHA_SECRET_KEY=
            - FRONT_MAIN_PAGE=
            - EMAIL_USE_TLS=
            - EMAIL_HOST=
            - EMAIL_HOST_USER=
            - EMAIL_HOST_PASSWORD=
            - EMAIL_FROM=
            - EMAIL_PORT=
            - CORS_ORIGIN_REGEX_WHITELIST=
        depends_on:
            - db
    db:
        image: postgres:12.3
        environment:
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=




