version: '3.8'
services:
    debt-manager:
        build:
            context: .
            network: host
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: always
        command: bash -c "/code/wait-for-it/wait-for-it.sh db:5432 --timeout=600 --strict -- python manage.py migrate --noinput && pytest -v && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000
        environment:
            - SECRET_KEY=
            - GOOGLE_RECAPTCHA_SECRET_KEY=
            - FRONT_MAIN_PAGE=
            - EMAIL_USE_TLS=
            - EMAIL_HOST=
            - EMAIL_HOST_USER=
            - EMAIL_HOST_PASSWORD=
            - EMAIL_FROM=
            - EMAIL_PORT=
            - ALLOWED_HOSTS=
            - CORS_ORIGIN_REGEX_WHITELIST=
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=
            - DEBUG=
            - ADMIN_NAME=
            - ADMIN_EMAIL=
            - ADMIN_PASSWORD=
        depends_on:
            - db
    db:
        image: postgres:13.1
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: always
        volumes:
            - ./databases/postgre:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=
            - POSTGRES_USER=
            - POSTGRES_PASSWORD=




